-- begin BP_BPM_PROFILE_USER
alter table BP_BPM_PROFILE_USER add constraint FK_BP_BPM_PROFILE_USER_ON_EXT_PROC_ROLE foreign key (EXT_PROC_ROLE_ID) references BPM_PROC_ROLE(ID)^
alter table BP_BPM_PROFILE_USER add constraint FK_BP_BPM_PROFILE_USER_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table BP_BPM_PROFILE_USER add constraint FK_BP_BPM_PROFILE_USER_ON_BPM_PROFILE foreign key (BPM_PROFILE_ID) references BP_BPM_PROFILE(ID)^
create index IDX_BP_BPM_PROFILE_USER_ON_EXT_PROC_ROLE on BP_BPM_PROFILE_USER (EXT_PROC_ROLE_ID)^
create index IDX_BP_BPM_PROFILE_USER_ON_USER on BP_BPM_PROFILE_USER (USER_ID)^
create index IDX_BP_BPM_PROFILE_USER_ON_BPM_PROFILE on BP_BPM_PROFILE_USER (BPM_PROFILE_ID)^
-- end BP_BPM_PROFILE_USER
-- begin BP_BPM_PROFILE_ROLE
alter table BP_BPM_PROFILE_ROLE add constraint FK_BP_BPM_PROFILE_ROLE_ON_ROLE foreign key (ROLE_ID) references SEC_ROLE(ID)^
alter table BP_BPM_PROFILE_ROLE add constraint FK_BP_BPM_PROFILE_ROLE_ON_PROC_ROLE foreign key (PROC_ROLE_ID) references BPM_PROC_ROLE(ID)^
alter table BP_BPM_PROFILE_ROLE add constraint FK_BP_BPM_PROFILE_ROLE_ON_BPM_PROFILE foreign key (BPM_PROFILE_ID) references BP_BPM_PROFILE(ID)^
create index IDX_BP_BPM_PROFILE_ROLE_ON_ROLE on BP_BPM_PROFILE_ROLE (ROLE_ID)^
create index IDX_BP_BPM_PROFILE_ROLE_ON_PROC_ROLE on BP_BPM_PROFILE_ROLE (PROC_ROLE_ID)^
create index IDX_BP_BPM_PROFILE_ROLE_ON_BPM_PROFILE on BP_BPM_PROFILE_ROLE (BPM_PROFILE_ID)^
-- end BP_BPM_PROFILE_ROLE
-- begin BP_BPM_PROFILE_TASK
alter table BP_BPM_PROFILE_TASK add constraint FK_BP_BPM_PROFILE_TASK_ON_PROC_TASK foreign key (PROC_TASK_ID) references BPM_PROC_TASK(ID)^
alter table BP_BPM_PROFILE_TASK add constraint FK_BP_BPM_PROFILE_TASK_ON_EMAIL_TEMPLATE foreign key (EMAIL_TEMPLATE_ID) references EMAILTEMPLATES_EMAIL_TEMPLATE(ID)^
alter table BP_BPM_PROFILE_TASK add constraint FK_BP_BPM_PROFILE_TASK_ON_BPM_PROFILE foreign key (BPM_PROFILE_ID) references BP_BPM_PROFILE(ID)^
create index IDX_BP_BPM_PROFILE_TASK_ON_PROC_TASK on BP_BPM_PROFILE_TASK (PROC_TASK_ID)^
create index IDX_BP_BPM_PROFILE_TASK_ON_EMAIL_TEMPLATE on BP_BPM_PROFILE_TASK (EMAIL_TEMPLATE_ID)^
create index IDX_BP_BPM_PROFILE_TASK_ON_BPM_PROFILE on BP_BPM_PROFILE_TASK (BPM_PROFILE_ID)^
-- end BP_BPM_PROFILE_TASK
-- begin BP_BPM_PROFILE
alter table BP_BPM_PROFILE add constraint FK_BP_BPM_PROFILE_ON_PROC_MODEL foreign key (PROC_MODEL_ID) references BPM_PROC_MODEL(ID)^
alter table BP_BPM_PROFILE add constraint FK_BP_BPM_PROFILE_ON_PROC_DEFINITION foreign key (PROC_DEFINITION_ID) references BPM_PROC_DEFINITION(ID)^
create index IDX_BP_BPM_PROFILE_ON_PROC_MODEL on BP_BPM_PROFILE (PROC_MODEL_ID)^
create index IDX_BP_BPM_PROFILE_ON_PROC_DEFINITION on BP_BPM_PROFILE (PROC_DEFINITION_ID)^
-- end BP_BPM_PROFILE
