-- begin BP_BPM_PROFILE
alter table BP_BPM_PROFILE add constraint FK_BP_BPM_PROFILE_PROC_DEFINITION foreign key (PROC_DEFINITION_ID) references BPM_PROC_DEFINITION(ID)^
create index IDX_BP_BPM_PROFILE_PROC_DEFINITION on BP_BPM_PROFILE (PROC_DEFINITION_ID)^
-- end BP_BPM_PROFILE
-- begin BP_BPM_PROFILE_ACTOR
alter table BP_BPM_PROFILE_ACTOR add constraint FK_BP_BPM_PROFILE_ACTOR_PROC_ROLE foreign key (PROC_ROLE_ID) references BPM_PROC_ROLE(ID)^
alter table BP_BPM_PROFILE_ACTOR add constraint FK_BP_BPM_PROFILE_ACTOR_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table BP_BPM_PROFILE_ACTOR add constraint FK_BP_BPM_PROFILE_ACTOR_SEC_ROLE foreign key (SEC_ROLE_ID) references SEC_ROLE(ID)^
alter table BP_BPM_PROFILE_ACTOR add constraint FK_BP_BPM_PROFILE_ACTOR_BPM_PROFILE foreign key (BPM_PROFILE_ID) references BP_BPM_PROFILE(ID)^
create index IDX_BP_BPM_PROFILE_ACTOR_PROC_ROLE on BP_BPM_PROFILE_ACTOR (PROC_ROLE_ID)^
create index IDX_BP_BPM_PROFILE_ACTOR_USER on BP_BPM_PROFILE_ACTOR (USER_ID)^
create index IDX_BP_BPM_PROFILE_ACTOR_SEC_ROLE on BP_BPM_PROFILE_ACTOR (SEC_ROLE_ID)^
create index IDX_BP_BPM_PROFILE_ACTOR_BPM_PROFILE on BP_BPM_PROFILE_ACTOR (BPM_PROFILE_ID)^
-- end BP_BPM_PROFILE_ACTOR

-- begin BP_BPM_PROFILE_NOTIFICATION
alter table BP_BPM_PROFILE_NOTIFICATION add constraint FK_BP_BPM_PROFILE_NOTIFICATION_EMAIL_TEMPLATE foreign key (EMAIL_TEMPLATE_ID) references EMAILTEMPLATES_EMAIL_TEMPLATE(ID)^
alter table BP_BPM_PROFILE_NOTIFICATION add constraint FK_BP_BPM_PROFILE_NOTIFICATION_BPM_PROFILE foreign key (BPM_PROFILE_ID) references BP_BPM_PROFILE(ID)^
create index IDX_BP_BPM_PROFILE_NOTIFICATION_EMAIL_TEMPLATE on BP_BPM_PROFILE_NOTIFICATION (EMAIL_TEMPLATE_ID)^
create index IDX_BP_BPM_PROFILE_NOTIFICATION_BPM_PROFILE on BP_BPM_PROFILE_NOTIFICATION (BPM_PROFILE_ID)^
-- end BP_BPM_PROFILE_NOTIFICATION
