alter table BP_BPM_PROFILE_ACTOR add constraint FK_BP_BPM_PROFILE_ACTOR_PROC_ROLE foreign key (PROC_ROLE_ID) references BPM_PROC_ROLE(ID);
alter table BP_BPM_PROFILE_ACTOR add constraint FK_BP_BPM_PROFILE_ACTOR_USER foreign key (USER_ID) references SEC_USER(ID);
alter table BP_BPM_PROFILE_ACTOR add constraint FK_BP_BPM_PROFILE_ACTOR_SEC_ROLE foreign key (SEC_ROLE_ID) references SEC_ROLE(ID);
alter table BP_BPM_PROFILE_ACTOR add constraint FK_BP_BPM_PROFILE_ACTOR_BPM_PROFILE foreign key (BPM_PROFILE_ID) references BP_BPM_PROFILE(ID);
create index IDX_BP_BPM_PROFILE_ACTOR_PROC_ROLE on BP_BPM_PROFILE_ACTOR (PROC_ROLE_ID);
create index IDX_BP_BPM_PROFILE_ACTOR_USER on BP_BPM_PROFILE_ACTOR (USER_ID);
create index IDX_BP_BPM_PROFILE_ACTOR_SEC_ROLE on BP_BPM_PROFILE_ACTOR (SEC_ROLE_ID);
create index IDX_BP_BPM_PROFILE_ACTOR_BPM_PROFILE on BP_BPM_PROFILE_ACTOR (BPM_PROFILE_ID);
