alter table BP_BPM_PROFILE_USER add constraint FK_BP_BPM_PROFILE_USER_ON_BPM_PROFILE foreign key (BPM_PROFILE_ID) references BP_BPM_PROFILE(ID);
create index IDX_BP_BPM_PROFILE_USER_ON_BPM_PROFILE on BP_BPM_PROFILE_USER (BPM_PROFILE_ID);
