alter table BP_BPM_PROFILE_TASK add constraint FK_BP_BPM_PROFILE_TASK_ON_PROC_TASK foreign key (PROC_TASK_ID) references BPM_PROC_TASK(ID);
alter table BP_BPM_PROFILE_TASK add constraint FK_BP_BPM_PROFILE_TASK_ON_EMAIL_TEMPLATE foreign key (EMAIL_TEMPLATE_ID) references EMAILTEMPLATES_EMAIL_TEMPLATE(ID);
alter table BP_BPM_PROFILE_TASK add constraint FK_BP_BPM_PROFILE_TASK_ON_BPM_PROFILE foreign key (BPM_PROFILE_ID) references BP_BPM_PROFILE(ID);
create index IDX_BP_BPM_PROFILE_TASK_ON_PROC_TASK on BP_BPM_PROFILE_TASK (PROC_TASK_ID);
create index IDX_BP_BPM_PROFILE_TASK_ON_EMAIL_TEMPLATE on BP_BPM_PROFILE_TASK (EMAIL_TEMPLATE_ID);
create index IDX_BP_BPM_PROFILE_TASK_ON_BPM_PROFILE on BP_BPM_PROFILE_TASK (BPM_PROFILE_ID);
