alter table BP_BPM_PROFILE_USER add constraint FK_BP_BPM_PROFILE_USER_ON_EXT_PROC_ROLE foreign key (EXT_PROC_ROLE_ID) references BPM_PROC_ROLE(ID);
create index IDX_BP_BPM_PROFILE_USER_ON_EXT_PROC_ROLE on BP_BPM_PROFILE_USER (EXT_PROC_ROLE_ID);
