alter table BP_BPM_PROFILE_ROLE add constraint FK_BP_BPM_PROFILE_ROLE_ON_ROLE foreign key (ROLE_ID) references SEC_ROLE(ID);
alter table BP_BPM_PROFILE_ROLE add constraint FK_BP_BPM_PROFILE_ROLE_ON_PROC_ROLE foreign key (PROC_ROLE_ID) references BPM_PROC_ROLE(ID);
alter table BP_BPM_PROFILE_ROLE add constraint FK_BP_BPM_PROFILE_ROLE_ON_BPM_PROFILE foreign key (BPM_PROFILE_ID) references BP_BPM_PROFILE(ID);
create index IDX_BP_BPM_PROFILE_ROLE_ON_ROLE on BP_BPM_PROFILE_ROLE (ROLE_ID);
create index IDX_BP_BPM_PROFILE_ROLE_ON_PROC_ROLE on BP_BPM_PROFILE_ROLE (PROC_ROLE_ID);
create index IDX_BP_BPM_PROFILE_ROLE_ON_BPM_PROFILE on BP_BPM_PROFILE_ROLE (BPM_PROFILE_ID);
