alter table BP_BPM_PROFILE add constraint FK_BP_BPM_PROFILE_ON_PROC_DEFINITION foreign key (PROC_DEFINITION_ID) references BPM_PROC_DEFINITION(ID);
create index IDX_BP_BPM_PROFILE_ON_PROC_DEFINITION on BP_BPM_PROFILE (PROC_DEFINITION_ID);
